date.timezone = America/Bogota
display_errors = Off
log_errors = On
memory_limit = 256M
max_execution_time = 60
upload_max_filesize = 10M
post_max_size = 55M
max_file_uploads = 5
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1
expose_php = Off
